<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "mautic"
 *
 * Auto generated by Extension Builder 2014-12-04
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Mautic Tracker',
	'description' => 'Tracker from Mautic',
	'category' => 'plugin',
	'author' => '',
	'author_email' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '',
	'constraints' => array(
		'depends' => array(
            'php' => '5.3.0-0.0.0',
            'typo3' => '4.7.4-0.0.0',
            'extbase' => '0.0.0-0.0.0',
            'fluid' => '0.0.0-0.0.0',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);